#!/usr/bin/env bash
# Issue #2836: the release gate must not decide a branch through a pipe that can
# die of SIGPIPE.
#
# WHAT WENT WRONG
# ---------------
# The scheduled D37 release gate (REV run 35461332171) reported
#
#   Instrumentation failure reason: the app2 instrumented suite did not report
#   an 'OK (N tests)' summary with N >= 1
#
# on a suite that PASSED — the run's own artifact carries `OK (91 tests)` at
# line 1385, 96 tests / 5 quarantine skips / 0 failures. The guard that emitted
# that reason was
#
#   if ! printf '%s\n' "$output" | grep -Eq '^OK \([1-9][0-9]* tests?\)'; then
#
# inside a step whose first line is `set -euo pipefail`. The unfiltered app2
# suite's `$output` is 67,708 bytes — larger than the 64 KiB pipe buffer — so
# `printf` is STILL WRITING when `grep -q` matches near the end and exits
# immediately. `printf` takes SIGPIPE, the pipeline's status becomes 141,
# `pipefail` propagates it, and the leading `!` turns "grep matched" into "the
# guard failed". A passing suite reds an unbypassable gate, and the rate grows
# with every test added to the suite. Measured on this repo's fixture of the
# run's own shape — a race, so a sample, not a constant: two independent runs
# gave 13 and 10 false failures per 60 pre-fix step runs, and 0 in 60 after.
#
# THE FIX THIS GUARD PINS
# -----------------------
# Read the variable through a here-string — `grep -Eq '…' <<<"$output"`. A
# here-string is a file the shell hands grep; there is no second process to
# signal, so early exit cannot poison the status. Every quiet grep over a shell
# variable in scripts/pre-release-confidence-gate.sh uses that shape.
#
# WHAT IS CHECKED
# ---------------
#   C1  STATIC, TOTAL. No `printf '%s\n' "$VAR" | grep <flags containing q>`
#       anywhere in the gate — single-line OR split across two lines. The
#       two-line spelling is not hypothetical: the original triage table listed
#       seven sites and MISSED the eighth
#       (instrumentation_has_gl_compose_failure_signature) precisely because it
#       was split. A hand-kept site list is what let this class survive; this is
#       a scan, so a new site cannot be added without turning it red.
#   C2  BEHAVIOURAL, PER SITE, ON THE REAL EMITTED BYTES. The app2 suite step is
#       generated by a heredoc; this guard expands that heredoc exactly as the
#       gate does (nothing is transcribed — the idiom of
#       scripts/test-release-gate-summary.sh) and, for EVERY quiet grep over
#       `$output` in the emitted script, runs the real command under
#       `set -o pipefail` against a >64 KiB input whose matching line is FIRST.
#       Two arms: the real here-string shape must exit 0, and the mechanically
#       reverted pipe twin must exit 141. The revert arm is what proves this
#       check can see the defect, and it is DETERMINISTIC — with the match on
#       line 1 and megabytes still queued behind it, `printf` cannot finish
#       before grep exits, so there is no race to lose. Each site needs a
#       fixture keyed by its grep pattern; an uncovered site is a RED, so the
#       coverage cannot silently go partial.
#   C3  BEHAVIOURAL, END TO END. The real emitted step runs against a stub adb
#       that replays a captured-shape instrumentation output, and the branch it
#       takes plus the reason text it prints are asserted for four outcomes:
#       a passing suite (looped, because THAT is the incident), OK (0 tests),
#       no OK summary at all, and failure markers. This is what pins the reason
#       strings: change one and this goes red.
#   C5  BEHAVIOURAL, END TO END, BOTH SHAPES, DETERMINISTIC. The same emitted
#       step and the same passing-suite bytes are run twice — as shipped, and
#       with every quiet grep mechanically reverted to the pre-#2836 pipe. The
#       shipped shape must accept; the reverted twin must REJECT a suite that
#       passed, for a reason its own input falsifies. This is the incident
#       itself, with the race engineered out of it by putting the markers on
#       line 1 behind ~2.4 MiB of filler.
#   C4  The one grep over `$output` that is deliberately NOT quiet — the
#       `grep -E '^OK \([0-9]+ tests?\)'` that ECHOES the summary into the gate
#       log — must stay non-quiet. It reads to EOF, so it never raced; making it
#       `-q` would both re-open nothing and silently delete the gate's evidence
#       line.
#
# RESIDUAL GAP (stated, not hidden): C1 knows the `printf | grep -q` spelling.
# Any other early-exiting reader behind a pipe from a large variable (`| head`,
# `| grep -m1`, `| sed -n 1p`) would race the same way and is not detected. No
# such site exists in the gate today.
#
# Usage: scripts/check-gate-pipe-buffer-race.sh [--self-test] [GATE_PATH]
set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
SELF_PATH="$SCRIPT_DIR/$(basename -- "${BASH_SOURCE[0]}")"
DEFAULT_GATE="$ROOT_DIR/scripts/pre-release-confidence-gate.sh"

# The step heredoc interpolates exactly these names. Expansion runs under
# `set -u`, so a NEW interpolated variable fails loudly here instead of being
# silently expanded to the empty string in a check that then proves nothing.
readonly -a HEREDOC_VARIABLES=(
  ADB
  APP2_INSTRUMENTED_SUITE_LABEL
  APP_WALKTHROUGH_GL_REBOOT_ATTEMPTS
  APP_WALKTHROUGH_GL_REBOOT_BOOT_TIMEOUT_SECONDS
  APP_WALKTHROUGH_INSTRUMENTATION_ATTEMPTS
  APP_WALKTHROUGH_TRANSPORT_RECOVERY_ATTEMPTS
  diagnostics_file
  full_logcat_file
)

# One matching sample line per guarded grep pattern. Keyed by the pattern text
# as it appears in the EMITTED step, so editing a pattern without extending this
# table is a red (C2 "no fixture"), not a silently skipped site.
pattern_sample() {
  case "$1" in
    '(^FAILURES!!!$|^FAILURE: |^INSTRUMENTATION_STATUS_CODE: -[12]$|^INSTRUMENTATION_STATUS: stack=|^[[:space:]]*at (com[.]pocketshell|androidx[.]test|org[.]junit|kotlin[.]|java[.]|android[.])|^[[:alnum:]_.]*(Exception|Error): |^Process crashed[.])')
      printf 'FAILURES!!!\n' ;;
    'No compose hierarchies found|the Activity that calls setContent did not launch')
      printf 'No compose hierarchies found\n' ;;
    'INSTRUMENTATION_CODE: -1')
      printf 'INSTRUMENTATION_CODE: -1\n' ;;
    '^OK \(0 tests\)')
      printf 'OK (0 tests)\n' ;;
    '^OK \([1-9][0-9]* tests?\)')
      printf 'OK (91 tests)\n' ;;
    'Process crashed')
      printf 'Process crashed.\n' ;;
    *) return 1 ;;
  esac
}

FAILURES=0
CHECKS=0

pass() {
  CHECKS=$((CHECKS + 1))
  printf '  ok   %s\n' "$1"
}

fail() {
  FAILURES=$((FAILURES + 1))
  printf 'FAIL: %s\n' "$1" >&2
}

# --------------------------------------------------------------------------
# C1 — static, total: no quiet grep fed by a pipe from a variable.
# --------------------------------------------------------------------------
grep_flags_are_quiet() {
  # "$1" is a flag cluster such as -q, -Eq, -Eiq, -qi.
  [[ "$1" == -*q* ]]
}

check_no_piped_quiet_grep() {
  local gate="$1"
  local -a source=()
  mapfile -t source <"$gate"

  local i line next flags offenders=0 here_string_sites=0
  for ((i = 0; i < ${#source[@]}; i++)); do
    line="${source[i]}"
    if [[ "$line" =~ grep[[:space:]]+(-[A-Za-z]+)[[:space:]]+.*\<\<\<\" ]]; then
      grep_flags_are_quiet "${BASH_REMATCH[1]}" && here_string_sites=$((here_string_sites + 1))
    fi
    [[ "$line" == *"printf '%s\\n' \""*'|'* ]] || continue
    flags=""
    if [[ "$line" =~ \|[[:space:]]*grep[[:space:]]+(-[A-Za-z]+)[[:space:]] ]]; then
      flags="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ \|[[:space:]]*$ ]]; then
      next="${source[i + 1]:-}"
      if [[ "$next" =~ ^[[:space:]]*grep[[:space:]]+(-[A-Za-z]+)[[:space:]] ]]; then
        flags="${BASH_REMATCH[1]}"
      fi
    fi
    [[ -n "$flags" ]] || continue
    grep_flags_are_quiet "$flags" || continue
    offenders=$((offenders + 1))
    fail "$(basename "$gate"):$((i + 1)) pipes a variable into a quiet grep (grep $flags): under 'set -o pipefail' the writer dies of SIGPIPE once the variable exceeds the 64 KiB pipe buffer and the branch inverts (issue #2836). Use: grep $flags '…' <<<\"\$var\""
  done

  if ((offenders > 0)); then
    return 1
  fi
  if ((here_string_sites == 0)); then
    fail "$(basename "$gate") contains no 'grep -…q … <<<\"\$var\"' site at all — the guard has lost its subject and would pass vacuously"
    return 1
  fi
  pass "C1 no piped quiet grep in $(basename "$gate") ($here_string_sites here-string quiet site(s))"
}

# --------------------------------------------------------------------------
# Emit the REAL app2 suite step, exactly as the gate generates it.
# --------------------------------------------------------------------------
emit_suite_step() {
  local gate="$1" adb="$2" diagnostics="$3" logcat="$4"
  local body
  body="$(awk '
    /^[[:space:]]*cat <<RUN_SCRIPT$/ { inside = 1; next }
    inside && /^RUN_SCRIPT$/ { exit }
    inside { print }
  ' "$gate")"
  if [[ -z "$body" ]]; then
    fail "could not extract the RUN_SCRIPT heredoc from $gate — the app2 suite step moved or was renamed"
    return 1
  fi

  local referenced
  # shellcheck disable=SC2016  # '${' is a literal character set for tr, not an expansion
  referenced="$(grep -oP "(?<!\\\\)\\\$\{?[A-Za-z_][A-Za-z0-9_]*" <<<"$body" | tr -d '${' | sort -u)"
  local expected
  expected="$(printf '%s\n' "${HEREDOC_VARIABLES[@]}" | sort -u)"
  if [[ "$referenced" != "$expected" ]]; then
    fail "the RUN_SCRIPT heredoc interpolates a different variable set than this guard seeds; update HEREDOC_VARIABLES. diff:
$(diff <(printf '%s\n' "$expected") <(printf '%s\n' "$referenced") || true)"
    return 1
  fi

  # Every name seeded below is read by the `eval "cat <<RUN_SCRIPT …"` that
  # follows — an expansion ShellCheck cannot see.
  # shellcheck disable=SC2034
  (
    set -u
    ADB="$adb"
    APP2_INSTRUMENTED_SUITE_LABEL="app2-instrumented-suite"
    APP_WALKTHROUGH_INSTRUMENTATION_ATTEMPTS=3
    APP_WALKTHROUGH_TRANSPORT_RECOVERY_ATTEMPTS=3
    APP_WALKTHROUGH_GL_REBOOT_ATTEMPTS=2
    APP_WALKTHROUGH_GL_REBOOT_BOOT_TIMEOUT_SECONDS=300
    diagnostics_file="$diagnostics"
    full_logcat_file="$logcat"
    eval "cat <<RUN_SCRIPT
$body
RUN_SCRIPT"
  )
}

# --------------------------------------------------------------------------
# C2 — per-site behaviour on a >64 KiB input, plus the reverted-twin counter-arm.
# --------------------------------------------------------------------------
write_oversize_fixture() {
  # The matching line goes FIRST and ~2.4 MiB of non-matching filler follows, so
  # a quiet grep exits after one line with 37 pipe buffers still queued behind
  # it. That is what makes the reverted-twin arm deterministic rather than a
  # ~1-20% race: `printf` cannot possibly finish its write before grep leaves.
  local path="$1" first_line="$2"
  if [[ ! -s "$SANDBOX/filler.txt" ]]; then
    awk 'BEGIN { line = ""; for (c = 0; c < 79; c++) line = line "z"; for (i = 0; i < 30000; i++) print line }' \
      >"$SANDBOX/filler.txt"
  fi
  {
    printf '%s\n' "$first_line"
    cat "$SANDBOX/filler.txt"
  } >"$path"
}

run_pipeline_arm() {
  # Runs one grep command against $output under pipefail and echoes its status.
  local fixture="$1" command="$2"
  local runner="$SANDBOX/arm.sh"
  {
    printf 'set -uo pipefail\n'
    # shellcheck disable=SC2016  # emitted verbatim into the runner script, not expanded here
    printf 'output="$(cat "$1")"\n'
    printf 'set +e\n'
    printf '%s\n' "$command"
    printf 'exit $?\n'
  } >"$runner"
  bash "$runner" "$fixture" >/dev/null 2>&1
  printf '%s' "$?"
}

check_site_behaviour() {
  local emitted="$1"
  local site_re='grep[[:space:]]+(-[A-Za-z]+)[[:space:]]+'\''(.*)'\''[[:space:]]+<<<"(\$[A-Za-z_][A-Za-z0-9_]*)"'
  local line flags pattern var sample fixture rc sites=0 bad=0

  while IFS= read -r line; do
    [[ "$line" =~ $site_re ]] || continue
    flags="${BASH_REMATCH[1]}"
    pattern="${BASH_REMATCH[2]}"
    var="${BASH_REMATCH[3]}"
    grep_flags_are_quiet "$flags" || continue
    sites=$((sites + 1))

    if ! sample="$(pattern_sample "$pattern")"; then
      fail "C2 has no fixture for guarded pattern '$pattern' — add a matching sample to pattern_sample() so the site is actually exercised"
      bad=$((bad + 1))
      continue
    fi
    sample="${sample%$'\n'}"
    fixture="$SANDBOX/site-$sites.txt"
    write_oversize_fixture "$fixture" "$sample"

    rc="$(run_pipeline_arm "$fixture" "grep $flags '$pattern' <<<\"$var\"")"
    if [[ "$rc" != "0" ]]; then
      fail "C2 here-string site 'grep $flags $pattern' returned $rc on a matching >64 KiB input; expected 0"
      bad=$((bad + 1))
    fi

    rc="$(run_pipeline_arm "$fixture" "printf '%s\\n' \"$var\" | grep $flags '$pattern'")"
    if [[ "$rc" != "141" ]]; then
      fail "C2 counter-arm: the reverted pipe twin of 'grep $flags $pattern' returned $rc, expected 141 (SIGPIPE) — the check can no longer see the defect it exists for"
      bad=$((bad + 1))
    fi
  done <"$emitted"

  if ((sites == 0)); then
    fail "C2 found no quiet here-string grep over a variable in the emitted app2 suite step"
    return 1
  fi
  ((bad == 0)) || return 1
  pass "C2 $sites guarded site(s) matched on a >64 KiB input; every reverted pipe twin died 141"
}

# --------------------------------------------------------------------------
# C5 — the whole gate decision, end to end, both shapes, DETERMINISTICALLY.
#
# The same emitted step, the same passing-suite bytes, run twice: once as it
# ships, once with every quiet grep mechanically reverted to the pre-#2836 pipe.
# The fixture puts its markers on the FIRST lines with ~2.4 MiB queued behind
# them, so the reverted twin cannot win the race even once — `printf` is still
# writing when grep leaves. The twin then rejects a suite that passed, with a
# reason that is verifiably false about its own input. That is the incident,
# reduced to a pair of runs with no flakiness left in it.
# --------------------------------------------------------------------------
revert_to_pipe_shape() {
  local emitted="$1" reverted="$2"
  python3 - "$emitted" "$reverted" <<'REVERT_PY'
import re
import sys

site = re.compile(r'''grep (-[A-Za-z]*q[A-Za-z]*) ('[^']*') <<<"(\$[A-Za-z_][A-Za-z0-9_]*)"''')


def to_pipe(match):
    return "printf '%s\\n' \"" + match.group(3) + "\" | grep " + match.group(1) + " " + match.group(2)


text = open(sys.argv[1]).read()
reverted, count = site.subn(to_pipe, text)
if count == 0:
    sys.exit(3)
open(sys.argv[2], "w").write(reverted)
print(count)
REVERT_PY
}

check_both_shapes_end_to_end() {
  local emitted="$1"
  local reverted="$SANDBOX/suite-step-reverted.sh"
  local sites rc out

  if ! sites="$(revert_to_pipe_shape "$emitted" "$reverted")"; then
    fail "C5 could not build the pre-#2836 pipe twin of the emitted step"
    return 1
  fi
  if ! bash -n "$reverted"; then
    fail "C5 the reverted twin is not valid bash"
    return 1
  fi

  # A passing suite whose markers land on the first lines, with megabytes behind.
  local fixture="$SANDBOX/passing-early.txt"
  {
    printf 'OK (91 tests)\n'
    printf 'INSTRUMENTATION_CODE: -1\n'
    cat "$SANDBOX/filler.txt"
  } >"$fixture"
  if ! grep -Fq 'INSTRUMENTATION_CODE: -1' "$fixture"; then
    fail "C5 fixture does not contain INSTRUMENTATION_CODE: -1, so the twin's reason could not be shown to be false"
    return 1
  fi

  out="$SANDBOX/c5-shipped.out"
  rc="$(run_suite_step "$emitted" "$fixture" "$out")"
  if [[ "$rc" != "0" ]] || ! grep -Fq 'OK (91 tests)' "$out"; then
    fail "C5 the shipped step rejected a passing suite (rc=$rc): $(grep -m1 'Instrumentation failure reason' "$out" || printf 'no reason line')"
    return 1
  fi

  out="$SANDBOX/c5-reverted.out"
  rc="$(run_suite_step "$reverted" "$fixture" "$out")"
  if [[ "$rc" == "0" ]]; then
    fail "C5 counter-arm: the pre-#2836 pipe twin ($sites site(s) reverted) ACCEPTED the passing suite — with a >64 KiB input and the match on line 1 it must die of SIGPIPE, so this check can no longer see the defect it exists for"
    return 1
  fi
  if ! grep -Fq 'did not report INSTRUMENTATION_CODE: -1' "$out"; then
    fail "C5 counter-arm: the pipe twin failed for an unexpected reason: $(grep -m1 'Instrumentation failure reason' "$out" || printf 'no reason line')"
    return 1
  fi
  pass "C5 same bytes, both shapes: the shipped step accepts the passing suite; the $sites-site pipe twin rejects it as 'did not report INSTRUMENTATION_CODE: -1' — which its own input contains on line 2"
}

# --------------------------------------------------------------------------
# C3 — the real emitted step, end to end, against a stub adb.
# --------------------------------------------------------------------------
write_stub_adb() {
  cat >"$SANDBOX/adb" <<'STUB'
#!/usr/bin/env bash
if [ "${1:-}" = "shell" ] && [ "${2:-}" = "am" ] && [ "${3:-}" = "instrument" ]; then
  cat "$STUB_ADB_INSTRUMENT_OUTPUT"
  exit "${STUB_ADB_INSTRUMENT_STATUS:-0}"
fi
exit 0
STUB
  chmod +x "$SANDBOX/adb"
}

write_suite_output() {
  # A capture-shaped instrumentation output: >64 KiB of per-test status lines
  # with the summary at the END, exactly where the real suite puts it.
  local path="$1" summary="$2"
  {
    awk 'BEGIN {
      for (i = 0; i < 700; i++) {
        print "INSTRUMENTATION_STATUS: class=com.pocketshell.app2.journey.J01Journey"
        print "INSTRUMENTATION_STATUS_CODE: 0"
      }
    }'
    [[ -n "$summary" ]] && printf '\nTime: 1,006.315\n\n%s\n\n' "$summary"
    printf '\nINSTRUMENTATION_CODE: -1\n'
  } >"$path"
}

run_suite_step() {
  local emitted="$1" fixture="$2" out="$3"
  STUB_ADB_INSTRUMENT_OUTPUT="$fixture" bash "$emitted" >"$out" 2>&1
  printf '%s' "$?"
}

check_step_behaviour() {
  local emitted="$1"
  local loops="${POCKETSHELL_GATE_RACE_LOOPS:-60}"
  local fixture out rc bad=0 i misfires=0

  # (1) the incident: a passing suite, looped.
  fixture="$SANDBOX/pass.txt"
  write_suite_output "$fixture" "OK (91 tests)"
  local size
  size="$(wc -c <"$fixture")"
  if ((size <= 65536)); then
    fail "C3 passing-suite fixture is $size bytes — it must exceed the 64 KiB pipe buffer or it cannot reproduce #2836"
    return 1
  fi
  out="$SANDBOX/pass.out"
  for ((i = 1; i <= loops; i++)); do
    rc="$(run_suite_step "$emitted" "$fixture" "$out")"
    if [[ "$rc" != "0" ]] || ! grep -Fq 'OK (91 tests)' "$out"; then
      misfires=$((misfires + 1))
      if ((misfires == 1)); then
        fail "C3 a PASSING suite ($size-byte output, 'OK (91 tests)') was rejected by the gate step on iteration $i (rc=$rc): $(grep -m1 'Instrumentation failure reason' "$out" || printf 'no reason line')"
      fi
    fi
  done
  if ((misfires > 0)); then
    fail "C3 passing-suite step: $misfires/$loops runs failed a suite that passed — this is #2836"
    bad=$((bad + 1))
  fi

  # (2) OK (0 tests) — the vacuity refusal must still fire, by name.
  fixture="$SANDBOX/vacuous.txt"
  write_suite_output "$fixture" "OK (0 tests)"
  out="$SANDBOX/vacuous.out"
  rc="$(run_suite_step "$emitted" "$fixture" "$out")"
  if [[ "$rc" == "0" ]] || ! grep -Fq 'reported OK (0 tests)' "$out"; then
    fail "C3 'OK (0 tests)' must be refused with the vacuity reason (rc=$rc): $(grep -m1 'Instrumentation failure reason' "$out" || printf 'no reason line')"
    bad=$((bad + 1))
  fi

  # (3) no summary at all — the reason text this issue's false failure printed.
  fixture="$SANDBOX/nosummary.txt"
  write_suite_output "$fixture" ""
  out="$SANDBOX/nosummary.out"
  rc="$(run_suite_step "$emitted" "$fixture" "$out")"
  if [[ "$rc" == "0" ]] ||
    ! grep -Fq "did not report an 'OK (N tests)' summary with N >= 1" "$out"; then
    fail "C3 an output with no OK summary must be refused with the 'did not report an OK (N tests) summary' reason (rc=$rc): $(grep -m1 'Instrumentation failure reason' "$out" || printf 'no reason line')"
    bad=$((bad + 1))
  fi

  # (4) failure markers — a real red must still classify as one.
  fixture="$SANDBOX/failed.txt"
  write_suite_output "$fixture" "FAILURES!!!"
  out="$SANDBOX/failed.out"
  rc="$(run_suite_step "$emitted" "$fixture" "$out")"
  if [[ "$rc" == "0" ]] || ! grep -Fq 'with failure markers' "$out"; then
    fail "C3 a run carrying failure markers must be refused as a failure (rc=$rc): $(grep -m1 'Instrumentation failure reason' "$out" || printf 'no reason line')"
    bad=$((bad + 1))
  fi

  ((bad == 0)) || return 1
  pass "C3 emitted step: $loops/$loops passing-suite runs accepted, and the vacuous / no-summary / failure-marker refusals each fired by name"
}

# --------------------------------------------------------------------------
# C4 — the deliberately non-quiet summary echo.
# --------------------------------------------------------------------------
check_summary_echo_stays_loud() {
  local emitted="$1"
  local -a echoes=()
  mapfile -t echoes < <(grep -nF "'^OK \\([0-9]+ tests?\\)'" "$emitted" || true)
  if ((${#echoes[@]} != 1)); then
    fail "C4 expected exactly one 'OK (N tests)' summary echo in the emitted step, found ${#echoes[@]} — the gate log's evidence line moved or was deleted"
    return 1
  fi
  local flags=""
  [[ "${echoes[0]}" =~ grep[[:space:]]+(-[A-Za-z]+)[[:space:]] ]] && flags="${BASH_REMATCH[1]}"
  if [[ -z "$flags" ]] || grep_flags_are_quiet "$flags"; then
    fail "C4 the summary echo must stay a non-quiet, printing grep — it writes the gate log's 'OK (N tests)' evidence line, the artifact this issue was argued from: ${echoes[0]}"
    return 1
  fi
  pass "C4 the summary echo is still a printing grep $flags (reads to EOF: never raced, must keep printing)"
}

# --------------------------------------------------------------------------
run_checks() {
  local gate="$1"
  [[ -f "$gate" ]] || {
    fail "gate script not found: $gate"
    return 1
  }
  printf 'pre-release gate pipe-buffer race guard (issue #2836) — %s\n' "$gate"

  check_no_piped_quiet_grep "$gate" || return 1

  local emitted="$SANDBOX/suite-step.sh"
  write_stub_adb
  emit_suite_step "$gate" "$SANDBOX/adb" "$SANDBOX/diagnostics.txt" "$SANDBOX/logcat.txt" >"$emitted" || return 1
  if ! bash -n "$emitted"; then
    fail "the emitted app2 suite step is not valid bash"
    return 1
  fi

  check_summary_echo_stays_loud "$emitted" || return 1
  check_site_behaviour "$emitted" || return 1
  check_both_shapes_end_to_end "$emitted" || return 1
  check_step_behaviour "$emitted" || return 1

  printf 'PASS: %d check(s) on %s\n' "$CHECKS" "$(basename "$gate")"
}

main() {
  local gate="${1:-$DEFAULT_GATE}"
  SANDBOX="$(mktemp -d "${TMPDIR:-/tmp}/gate-pipe-buffer-race.XXXXXX")"
  trap 'rm -rf "$SANDBOX"' EXIT
  run_checks "$gate" || true
  ((FAILURES == 0)) || exit 1
}

# --------------------------------------------------------------------------
# --self-test: every check above must be able to go RED. Each mutant edits a
# COPY of the real gate; nothing here mutates the tree.
# --------------------------------------------------------------------------
SELFTEST_FAILURES=0

# Byte-exact substring replacement, so a mutant that no longer applies (because
# the line it targets moved) is a loud failure rather than a silent no-op.
mutate() {
  local src="$1" dst="$2" old="$3" new="$4"
  python3 - "$src" "$dst" "$old" "$new" <<'PY'
import sys
src, dst, old, new = sys.argv[1:5]
text = open(src).read()
if text.count(old) != 1:
    sys.stderr.write("mutation target occurs %d times, expected 1\n" % text.count(old))
    sys.exit(3)
open(dst, "w").write(text.replace(old, new))
PY
}

expect_red() {
  local label="$1" needle="$2" mutated="$3" tag="$4"
  local out="$SANDBOX/selftest-$tag.out" rc
  POCKETSHELL_GATE_RACE_LOOPS=5 bash "$SELF_PATH" "$mutated" >"$out" 2>&1
  rc=$?
  if ((rc == 0)); then
    printf '  MUTANT NOT CAUGHT: %s exited 0\n' "$label" >&2
    SELFTEST_FAILURES=$((SELFTEST_FAILURES + 1))
    return
  fi
  if ! grep -Fq "$needle" "$out"; then
    printf '  MUTANT CAUGHT WITH THE WRONG DIAGNOSTIC: %s (wanted "%s")\n' "$label" "$needle" >&2
    sed -n '1,12p' "$out" >&2
    SELFTEST_FAILURES=$((SELFTEST_FAILURES + 1))
    return
  fi
  printf '  ok   RED as expected: %s\n' "$label"
}

run_mutant() {
  local tag="$1" label="$2" needle="$3" old="$4" new="$5"
  local mutated="$SANDBOX/$tag.sh"
  if ! mutate "$DEFAULT_GATE" "$mutated" "$old" "$new"; then
    printf '  %s MUTATION DID NOT APPLY — its target line moved; the arm proves nothing\n' "$tag" >&2
    SELFTEST_FAILURES=$((SELFTEST_FAILURES + 1))
    return
  fi
  expect_red "$label" "$needle" "$mutated" "$tag"
}

self_test() {
  SANDBOX="$(mktemp -d "${TMPDIR:-/tmp}/gate-pipe-buffer-race-selftest.XXXXXX")"
  trap 'rm -rf "$SANDBOX"' EXIT
  [[ -f "$DEFAULT_GATE" ]] || {
    printf 'FAIL: gate script not found: %s\n' "$DEFAULT_GATE" >&2
    exit 1
  }
  printf 'pre-release gate pipe-buffer race guard --self-test (issue #2836)\n'

  printf '== control: the real gate, unmutated (expect PASS) ==\n'
  local control="$SANDBOX/control.sh"
  cp "$DEFAULT_GATE" "$control"
  if POCKETSHELL_GATE_RACE_LOOPS=5 bash "$SELF_PATH" "$control" >"$SANDBOX/control.out" 2>&1; then
    printf '  ok   PASS as expected\n'
  else
    printf '  CONTROL FAILED on the unmutated gate\n' >&2
    cat "$SANDBOX/control.out" >&2
    SELFTEST_FAILURES=$((SELFTEST_FAILURES + 1))
  fi

  printf '== mutants (each expects RED) ==\n'

  # M1 — the incident site itself, reverted to the racing pipe shape.
  run_mutant m1 \
    'M1 OK-summary site reverted to printf | grep -Eq' \
    'pipes a variable into a quiet grep' \
    $'    if ! grep -Eq \'^OK \\\\([1-9][0-9]* tests?\\\\)\' <<<"\\$output"; then' \
    $'    if ! printf \'%s\\n\' "\\$output" | grep -Eq \'^OK \\\\([1-9][0-9]* tests?\\\\)\'; then'

  # M2 — the site the original triage MISSED, back in its TWO-LINE spelling.
  # This is the arm that proves the scan sees the split shape, which is the
  # only reason that site was overlooked in the first place.
  run_mutant m2 \
    'M2 gl-compose site reverted to the TWO-LINE printf | grep -Eq' \
    'pipes a variable into a quiet grep' \
    $'  if grep -Eq \'No compose hierarchies found|the Activity that calls setContent did not launch\' <<<"\\$output"; then' \
    $'  if printf \'%s\\n\' "\\$output" |\n    grep -Eq \'No compose hierarchies found|the Activity that calls setContent did not launch\'; then'

  # M3 — a NEW guarded site whose pattern has no fixture. Coverage must not be
  # allowed to go partial in silence.
  run_mutant m3 \
    'M3 new guarded site with no fixture' \
    'has no fixture for guarded pattern' \
    $'should_retry_interrupted_instrumentation() {\n  [ "\\$instrument_status" -eq 255 ] || return 1' \
    $'should_retry_interrupted_instrumentation() {\n  grep -q \'a marker nobody wrote a fixture for\' <<<"\\$output" && return 1\n  [ "\\$instrument_status" -eq 255 ] || return 1'

  # M4 — the summary echo converted to a quiet here-string. C1 cannot see this
  # (it is not a pipe) and it is race-free — but the gate would stop printing the
  # 'OK (N tests)' evidence line this whole issue was argued from.
  run_mutant m4 \
    'M4 summary echo turned into a quiet grep' \
    'must stay a non-quiet, printing grep' \
    $'    printf \'%s\\n\' "\\$output" | grep -E \'^OK \\\\([0-9]+ tests?\\\\)\'' \
    $'    grep -Eq \'^OK \\\\([0-9]+ tests?\\\\)\' <<<"\\$output"'

  # M5 — the failure REASON text changed: C3 pins the strings the gate prints,
  # because the false reason is what made this issue diagnosable at all.
  run_mutant m5 \
    'M5 no-summary reason text changed' \
    "must be refused with the 'did not report an OK (N tests) summary' reason" \
    "did not report an 'OK (N tests)' summary with N >= 1" \
    'reported something else entirely'

  if ((SELFTEST_FAILURES != 0)); then
    printf 'FAIL: pipe-buffer race guard self-test: %d arm(s) behaved incorrectly\n' "$SELFTEST_FAILURES" >&2
    exit 1
  fi
  printf 'PASS: pipe-buffer race guard self-test (1 control + 5 mutants)\n'
}

case "${1:-}" in
  --help | -h)
    sed -n '1,81p' "$SELF_PATH" | sed 's/^# \{0,1\}//'
    ;;
  --self-test)
    self_test
    ;;
  *) main "$@" ;;
esac
