#!/usr/bin/env bash
# Run the packaged J10 file browser/editor journey against an isolated healthy
# Docker agents lane, then independently verify the bytes left on that host.
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$ROOT_DIR"
ANDROID_SDK="${ANDROID_SDK:-${ANDROID_SDK_ROOT:-${ANDROID_HOME:-/home/alexey/Android/Sdk}}}"
ADB="${ADB:-$ANDROID_SDK/platform-tools/adb}"
PORT=""
CONTAINER=""
SUFFIX="i2858files"
RUN_ID="j10files-$(date -u '+%Y%m%dT%H%M%S')"
PREPARE_ONLY=0
TEST_ONLY=0

fail() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }

usage() {
  cat <<'USAGE'
Usage: scripts/connected-js-files-docker.sh [--port PORT --container NAME] [options]

Build and run the packaged Android file browser/editor against a healthy Docker
SSH fixture. The run seeds a unique directory under /home/testuser, then checks
confined paths, symlink refusal, edit conflict preservation, transfer limits,
binary download bytes, and uploaded bytes on the host.

Options:
  --port PORT          Docker SSH port as reached from the Android emulator
  --container NAME     Healthy Docker agents container name
  --suffix TOKEN       Isolated Android package suffix (default: i2858files)
  --run-id ID          Unique fixture/artifact ID (generated by default)
  --prepare-only       Build app and androidTest APKs without Docker or AVD
  --test-only          Run previously built APKs
  --help               Show this help

The Docker port and container are required unless --prepare-only is selected.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port) [[ $# -ge 2 ]] || fail '--port needs a value'; PORT="$2"; shift 2 ;;
    --container) [[ $# -ge 2 ]] || fail '--container needs a value'; CONTAINER="$2"; shift 2 ;;
    --suffix) [[ $# -ge 2 ]] || fail '--suffix needs a value'; SUFFIX="$2"; shift 2 ;;
    --run-id) [[ $# -ge 2 ]] || fail '--run-id needs a value'; RUN_ID="$2"; shift 2 ;;
    --prepare-only) PREPARE_ONLY=1; shift ;;
    --test-only) TEST_ONLY=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

if [[ "$PREPARE_ONLY" != 1 ]]; then
  [[ "$PORT" =~ ^[0-9]{1,5}$ ]] && (( PORT >= 1 && PORT <= 65535 )) || fail '--port must be an integer between 1 and 65535'
  [[ "$CONTAINER" =~ ^[A-Za-z0-9_.-]+$ ]] || fail '--container must be a Docker container name'
fi
[[ "$SUFFIX" =~ ^[A-Za-z0-9._]+$ ]] || fail '--suffix must match [A-Za-z0-9._]+'
[[ "$RUN_ID" =~ ^[A-Za-z0-9][A-Za-z0-9_-]{2,38}$ ]] || fail 'run ID must be 3-39 path-safe characters'
(( PREPARE_ONLY + TEST_ONLY <= 1 )) || fail '--prepare-only and --test-only cannot be combined'
[[ -x "$ROOT_DIR/android/gradlew" ]] || fail 'generated Android Gradle wrapper is missing'
if [[ "$PREPARE_ONLY" != 1 ]]; then
  [[ -x "$ADB" ]] || fail "adb is missing or not executable: $ADB"
  [[ -f "$ROOT_DIR/tests/docker/test_key" ]] || fail 'committed Docker test key is missing'
fi

source "$ROOT_DIR/scripts/lib/disk-preflight.sh"
source "$ROOT_DIR/scripts/lib/gradle-output-lock.sh"
source "$ROOT_DIR/scripts/lib/avd-lock.sh"
pocketshell_disk_preflight "$ROOT_DIR/android" 'connected-js-files-docker.sh' || exit $?
pocketshell_acquire_gradle_output_lock "$ROOT_DIR/android" '' "connected-js-files-docker.sh suffix=$SUFFIX run=$RUN_ID"

if [[ "$TEST_ONLY" != 1 ]]; then
  command -v pnpm >/dev/null 2>&1 || fail 'pnpm is required to build the packaged web assets'
  "$ROOT_DIR/scripts/assemble-debug.sh" --suffix "$SUFFIX"
  "$ROOT_DIR/android/gradlew" -p "$ROOT_DIR/android" :app:assembleDebugAndroidTest \
    "-PpocketshellAppIdSuffix=$SUFFIX" --stacktrace --console=plain
fi

if [[ "$PREPARE_ONLY" == 1 ]]; then
  printf 'PASS: packaged file journey APKs prepared for suffix %s\n' "$SUFFIX"
  exit 0
fi

docker inspect "$CONTAINER" >/dev/null 2>&1 || fail "Docker fixture container is missing: $CONTAINER"
health="$(docker inspect --format '{{.State.Health.Status}}' "$CONTAINER" 2>/dev/null || true)"
[[ "$health" == healthy ]] || fail "Docker fixture must be healthy; $CONTAINER reports ${health:-no health status}"

if [[ -z "${ANDROID_SERIAL:-}" ]]; then
  mapfile -t online_emulators < <("$ADB" devices | awk '$1 ~ /^emulator-/ && $2 == "device" { print $1 }')
  (( ${#online_emulators[@]} == 1 )) || fail "expected one online emulator or ANDROID_SERIAL; found ${#online_emulators[@]}"
  export ANDROID_SERIAL="${online_emulators[0]}"
fi
[[ "$("$ADB" -s "$ANDROID_SERIAL" get-state 2>/dev/null || true)" == device ]] \
  || fail "selected Android device is not online: $ANDROID_SERIAL"
device_api="$("$ADB" -s "$ANDROID_SERIAL" shell getprop ro.build.version.sdk | tr -d '\r')"
[[ "$device_api" =~ ^[0-9]+$ ]] && (( device_api >= 35 )) \
  || fail "packaged file journey requires API 35+; device reports ${device_api:-unknown}"

export POCKETSHELL_AVD_LOCK_CONTINUOUS=1
export POCKETSHELL_AVD_LOCK_FILE="$(pocketshell_avd_lock_file_for_serial "$ROOT_DIR" "$ANDROID_SERIAL")"
pocketshell_acquire_avd_lock "$ROOT_DIR"
pocketshell_assert_avd_lock_owned "$POCKETSHELL_AVD_LOCK_FILE"

RESULTS_DIR="$ROOT_DIR/android/app/build/outputs/androidTest-results/connected/debug"
ARTIFACTS_DIR="$ROOT_DIR/android/app/build/outputs/js-files/$RUN_ID"
[[ ! -e "$ARTIFACTS_DIR" ]] || fail "refusing to overwrite existing run artifacts: $ARTIFACTS_DIR"
mkdir -p "$ARTIFACTS_DIR"
python3 - "$RESULTS_DIR" <<'PY'
from pathlib import Path
import shutil
import sys
results = Path(sys.argv[1])
if results.exists():
    shutil.rmtree(results)
PY

KEY_COPY="$ROOT_DIR/android/app/build/outputs/js-files-fixture-key"
mkdir -p "$(dirname -- "$KEY_COPY")"
install -m 600 "$ROOT_DIR/tests/docker/test_key" "$KEY_COPY"
ssh_opts=(-i "$KEY_COPY" -p "$PORT" -o BatchMode=yes -o ConnectTimeout=5 \
  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null)
REMOTE_ROOT="/home/testuser/.ps2858-files-$RUN_ID"
ssh_remote() { ssh -q "${ssh_opts[@]}" "testuser@127.0.0.1" "$1"; }
ssh_remote "test ! -e '$REMOTE_ROOT'" || fail "run-scoped remote fixture already exists: $REMOTE_ROOT"
ssh_remote "mkdir -m 700 '$REMOTE_ROOT' \
  && printf 'before-edit\\n' > '$REMOTE_ROOT/editable.txt' \
  && printf '\\000\\377BINARY' > '$REMOTE_ROOT/binary.bin' \
  && head -c 524289 /dev/zero > '$REMOTE_ROOT/large.bin' \
  && ln -s /etc/passwd '$REMOTE_ROOT/link.txt'"
printf 'Seeded Docker SFTP fixture: %s\n' "$REMOTE_ROOT"

encoded_key="$(base64 -w0 "$ROOT_DIR/tests/docker/test_key")"
test_class='com.pocketshell.app.smoke.J10FilesBrowseEditJourneyTest'
if "$ROOT_DIR/android/gradlew" -p "$ROOT_DIR/android" :app:connectedDebugAndroidTest \
    "-PpocketshellAppIdSuffix=$SUFFIX" \
    "-Pandroid.testInstrumentationRunnerArguments.class=$test_class" \
    -Pandroid.testInstrumentationRunnerArguments.sshHost=10.0.2.2 \
    "-Pandroid.testInstrumentationRunnerArguments.sshPort=$PORT" \
    "-Pandroid.testInstrumentationRunnerArguments.sshPrivateKeyBase64=$encoded_key" \
    "-Pandroid.testInstrumentationRunnerArguments.fileFixtureRoot=$REMOTE_ROOT" \
    --stacktrace --console=plain 2>&1 | tee "$ARTIFACTS_DIR/gradle-connected.log"; then
  :
else
  test_exit_code=$?
  mkdir -p "$RESULTS_DIR"
  "$ADB" -s "$ANDROID_SERIAL" logcat -d -v threadtime -t 6000 > "$ARTIFACTS_DIR/diagnostics-logcat.txt" 2>&1 || true
  "$ADB" -s "$ANDROID_SERIAL" exec-out screencap -p > "$ARTIFACTS_DIR/diagnostics-screen.png" 2>&1 || true
  printf 'FAILED: remote fixture retained for inspection at %s\n' "$REMOTE_ROOT" >&2
  exit "$test_exit_code"
fi

python3 - "$RESULTS_DIR" <<'PY'
from pathlib import Path
import sys
import xml.etree.ElementTree as ET
results = Path(sys.argv[1])
reports = list(results.rglob('TEST-*.xml')) if results.is_dir() else []
cases = []
for report in reports:
    root = ET.parse(report).getroot()
    suites = [root] if root.tag == 'testsuite' else list(root.findall('testsuite'))
    for suite in suites:
        cases.extend(suite.findall('testcase'))
matched = [case for case in cases if case.attrib.get('classname', '').rsplit('.', 1)[-1] == 'J10FilesBrowseEditJourneyTest']
if len(matched) != 1:
    raise SystemExit(f'expected exactly one J10 packaged test result; found {len(matched)}')
case = matched[0]
if list(case.iter('failure')) or list(case.iter('error')) or list(case.iter('skipped')):
    raise SystemExit('J10 packaged test has a failed, errored, or skipped result')
print(f'PASS: packaged J10 executed {case.attrib.get("classname")}#{case.attrib.get("name")}')
PY

[[ "$(ssh_remote "cat '$REMOTE_ROOT/editable.txt'")" == 'changed-remotely' ]] \
  || fail 'edit conflict handling overwrote the remote contents'
[[ "$(ssh_remote "cat '$REMOTE_ROOT/uploaded.txt'")" == 'upload-from-packaged-ui' ]] \
  || fail 'the Android upload did not persist exact bytes on the Docker host'
printf 'PASS: Docker host retained the concurrent edit and uploaded file bytes\n'

PACKAGE="com.pocketshell.app.$SUFFIX"
DEVICE_ARTIFACTS="files/js2858-files/${REMOTE_ROOT##*/}"
mkdir -p "$ARTIFACTS_DIR/device-screenshots"
for screenshot in files-home.png files-edit-conflict.png files-uploaded.png; do
  "$ADB" -s "$ANDROID_SERIAL" exec-out run-as "$PACKAGE" cat "$DEVICE_ARTIFACTS/$screenshot" \
    > "$ARTIFACTS_DIR/device-screenshots/$screenshot" \
    || fail "could not retrieve packaged Android screenshot: $screenshot"
  [[ -s "$ARTIFACTS_DIR/device-screenshots/$screenshot" ]] || fail "missing packaged screenshot: $screenshot"
done

ssh_remote "find '$REMOTE_ROOT' -depth -delete" >/dev/null
printf 'PASS: packaged J10 Docker journey completed. Artifacts: %s\n' "$ARTIFACTS_DIR"
pocketshell_release_all
