#!/usr/bin/env bash
# Run the packaged #3063 shared-picker account journey
# (SharedAccountPickerJourneyTest) on one owned API 35+ AVD, then collect
# same-run JUnit XML, screenshots and app logcat and check them. Like the
# #3020 account-sync lane it fakes only Google's account chooser and the sync
# API, in-process; no Docker fixture or network is needed.

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$ROOT_DIR"

ANDROID_SDK="${ANDROID_SDK:-${ANDROID_SDK_ROOT:-${ANDROID_HOME:-/home/alexey/Android/Sdk}}}"
ADB="${ADB:-$ANDROID_SDK/platform-tools/adb}"
SUFFIX="i3063picker"
RUN_ID="js3063-$(date -u '+%Y%m%dT%H%M%S')"
PREPARE_ONLY=0
TEST_ONLY=0
test_class="com.pocketshell.app.smoke.SharedAccountPickerJourneyTest"

usage() {
  cat <<'USAGE'
Usage: scripts/connected-js-account-picker.sh [--suffix TOKEN] [--run-id ID] [--prepare-only|--test-only]

Build and run the packaged shared-picker account journey
(SharedAccountPickerJourneyTest). Evidence lands in
android/app/build/outputs/js-account-picker/<run-id>/ and is checked by
scripts/check-js-account-picker-results.py.

Options:
  --suffix TOKEN   Isolate the debug package (default: i3063picker)
  --run-id ID      Unique artifact ID (generated by default)
  --prepare-only   Build the suffixed app and androidTest APKs, without an AVD
  --test-only      Run the already-prepared APKs on one API 35+ emulator
USAGE
}

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --suffix) [[ $# -ge 2 ]] || fail '--suffix needs a token'; SUFFIX="$2"; shift 2 ;;
    --run-id) [[ $# -ge 2 ]] || fail '--run-id needs a value'; RUN_ID="$2"; shift 2 ;;
    --prepare-only) PREPARE_ONLY=1; shift ;;
    --test-only) TEST_ONLY=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

[[ "$SUFFIX" =~ ^[A-Za-z0-9._]+$ ]] || fail "suffix must match [A-Za-z0-9._]+ (got: $SUFFIX)"
[[ "$RUN_ID" =~ ^[A-Za-z0-9][A-Za-z0-9_-]{2,48}$ ]] || fail 'run ID must be 3-49 path-safe characters'
(( PREPARE_ONLY + TEST_ONLY <= 1 )) || fail '--prepare-only and --test-only cannot be combined'
[[ -x "$ROOT_DIR/android/gradlew" ]] || fail 'generated android/gradlew is missing'
[[ -x "$ROOT_DIR/scripts/check-js-account-picker-results.py" ]] || fail 'packaged account-picker result verifier is missing'
"$ROOT_DIR/scripts/check-js-account-picker-results.py" --self-test

source "$ROOT_DIR/scripts/lib/disk-preflight.sh"
source "$ROOT_DIR/scripts/lib/gradle-output-lock.sh"
source "$ROOT_DIR/scripts/lib/avd-lock.sh"
source "$ROOT_DIR/scripts/lib/android-input-preflight.sh"

pocketshell_disk_preflight "$ROOT_DIR/android" 'connected-js-account-picker.sh' || exit $?
pocketshell_acquire_gradle_output_lock "$ROOT_DIR/android" '' "connected-js-account-picker.sh suffix=$SUFFIX run=$RUN_ID"

if [[ "$TEST_ONLY" != 1 ]]; then
  "$ROOT_DIR/scripts/assemble-debug.sh" --suffix "$SUFFIX"
  "$ROOT_DIR/android/gradlew" -p "$ROOT_DIR/android" :app:assembleDebugAndroidTest \
    "-PpocketshellAppIdSuffix=$SUFFIX" --stacktrace --console=plain
fi

if [[ "$PREPARE_ONLY" == 1 ]]; then
  printf 'PASS: packaged JS account-picker journey APKs prepared for suffix %s\n' "$SUFFIX"
  exit 0
fi

if [[ -z "${ANDROID_SERIAL:-}" ]]; then
  mapfile -t online_emulators < <("$ADB" devices | awk '$1 ~ /^emulator-/ && $2 == "device" { print $1 }')
  (( ${#online_emulators[@]} == 1 )) || fail "expected one online emulator or ANDROID_SERIAL; found ${#online_emulators[@]}"
  export ANDROID_SERIAL="${online_emulators[0]}"
fi
[[ "$("$ADB" -s "$ANDROID_SERIAL" get-state 2>/dev/null || true)" == device ]] \
  || fail "selected Android device is not online: $ANDROID_SERIAL"
device_api="$("$ADB" -s "$ANDROID_SERIAL" shell getprop ro.build.version.sdk | tr -d '\r')"
[[ "$device_api" =~ ^[0-9]+$ ]] && (( device_api >= 35 )) \
  || fail "the account-picker journey requires API 35+; $ANDROID_SERIAL reports API ${device_api:-unknown}"

export POCKETSHELL_AVD_LOCK_CONTINUOUS=1
export POCKETSHELL_AVD_LOCK_FILE="$(pocketshell_avd_lock_file_for_serial "$ROOT_DIR" "$ANDROID_SERIAL")"
pocketshell_acquire_avd_lock "$ROOT_DIR"
pocketshell_assert_avd_lock_owned "$POCKETSHELL_AVD_LOCK_FILE"

RESULTS_DIR="$ROOT_DIR/android/app/build/outputs/androidTest-results/connected/debug"
ARTIFACTS_DIR="$ROOT_DIR/android/app/build/outputs/js-account-picker/$RUN_ID"
[[ ! -e "$ARTIFACTS_DIR" ]] || fail "refusing to overwrite existing run artifacts: $ARTIFACTS_DIR"
rm -rf -- "$RESULTS_DIR"
mkdir -p "$ARTIFACTS_DIR/instrumentation-results" "$ARTIFACTS_DIR/device-screenshots"
# Injected taps must stay taps on a starved emulator (#2884, #2946).
pocketshell_android_apply_lane_settings "$ADB" "$ANDROID_SERIAL" "$ARTIFACTS_DIR/lane-settings.txt" \
  || fail "could not apply the lane input settings on $ANDROID_SERIAL"
# Same-run logcat only: the checker must not read an earlier run's lines.
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" logcat -c >/dev/null 2>&1 || true

SCREENSHOT_DIR="/sdcard/Pictures/PocketShell/JsAccountPicker/$RUN_ID"
printf 'Running packaged JS account-picker journey on %s (API %s), suffix %s, run %s\n' \
  "$ANDROID_SERIAL" "$device_api" "$SUFFIX" "$RUN_ID"
test_status=0
pocketshell_run_without_avd_lock_fd "$ROOT_DIR/android/gradlew" -p "$ROOT_DIR/android" :app:connectedDebugAndroidTest \
  "-PpocketshellAppIdSuffix=$SUFFIX" \
  "-Pandroid.testInstrumentationRunnerArguments.class=$test_class" \
  "-Pandroid.testInstrumentationRunnerArguments.screenshotRunId=$RUN_ID" \
  --stacktrace --console=plain || test_status=$?

shopt -s nullglob
junit_files=("$RESULTS_DIR"/TEST-*.xml)
shopt -u nullglob
(( ${#junit_files[@]} > 0 )) && cp -a -- "${junit_files[@]}" "$ARTIFACTS_DIR/instrumentation-results/"
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" logcat -d -v threadtime > "$ARTIFACTS_DIR/logcat.txt" 2>&1 || true
while IFS= read -r screenshot; do
  screenshot="${screenshot%$'\r'}"
  [[ "$screenshot" == *.png ]] || continue
  pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" pull "$SCREENSHOT_DIR/$screenshot" "$ARTIFACTS_DIR/device-screenshots/$screenshot" >/dev/null \
    || fail "could not retrieve packaged screenshot: $screenshot"
done < <(pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" shell "ls '$SCREENSHOT_DIR' 2>/dev/null" || true)

relative_screenshot_dir="Pictures/PocketShell/JsAccountPicker/$RUN_ID/"
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" shell \
  "content delete --uri content://media/external/images/media --where \"relative_path='$relative_screenshot_dir'\"" >/dev/null 2>&1 || true
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" shell "rm -rf '$SCREENSHOT_DIR'" >/dev/null 2>&1 || true

(( test_status == 0 )) || fail "connected account-picker journey failed (exit $test_status); evidence in $ARTIFACTS_DIR"

"$ROOT_DIR/scripts/check-js-account-picker-results.py" \
  --results-dir "$ARTIFACTS_DIR/instrumentation-results" \
  --screenshots-dir "$ARTIFACTS_DIR/device-screenshots" \
  --logcat "$ARTIFACTS_DIR/logcat.txt"
printf 'PASS: packaged JS account-picker journey completed. Artifacts: %s\n' "$ARTIFACTS_DIR"
