#!/usr/bin/env bash
# Run the packaged Android gateway journey (pocketshell#3086 slice 3,
# GatewayDockerJourneyTest): the app on one owned API 35+ emulator dials a
# host registered on the REAL PocketShell gateway, end to end, through a
# per-run Docker fixture (tests/docker/gateway/docker-compose.yml):
#
#   emulator --wss://localhost:PORT (adb reverse)--> TLS front (per-run test
#   CA) --> pocketshell-gateway (pinned source, registry + tunnel + broker
#   verification) <== pocketshell-link agent (enrolled like a user's host)
#   --> the host's own sshd on loopback (agents fixture: aplexer + CLI).
#
# The emulator has no route to the host's sshd. The pin the phone pairs with
# is the line the enrolled agent prints (`pocketshell gateway show
# --host-key`), checked here against the key file read from the host itself;
# the phone's own vault key is authorized on the host by the journey through
# the runner's controller (scripts/gateway-lane-fixture.py), which is also
# the host-side oracle. scripts/check-js-gateway-results.py checks the JUnit
# report and the controller's journal.
#
# The gateway repository is private: pass its checkout at the pinned commit
# (tests/docker/gateway/gateway-source.pin) with --gateway-src or
# POCKETSHELL_GATEWAY_SRC. A missing or different source fails; there is no
# skip.
#
# TLS: the prepare phase builds the suffixed debug APK with
# -PpocketshellGatewayTestCa and -PpocketshellGatewayTestPort, which make ONLY
# that build trust the run's test CA (for `localhost` only) and admit
# wss://localhost:<port> into the native gateway-origin allowlist
# (android/app/build.gradle, GatewayOriginAllowlist). Prepare and test must
# use the same --tls-port. Production and
# every other lane keep platform trust; the native transport's wss-only and
# hostname checks are unchanged.

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$ROOT_DIR"

ANDROID_SDK="${ANDROID_SDK:-${ANDROID_SDK_ROOT:-${ANDROID_HOME:-/home/alexey/Android/Sdk}}}"
ADB="${ADB:-$ANDROID_SDK/platform-tools/adb}"
GO="${GO:-go}"
SUFFIX="i3086gwlane"
RUN_ID="gw3086-$(date -u '+%Y%m%dT%H%M%S')"
GATEWAY_SRC="${POCKETSHELL_GATEWAY_SRC:-}"
# Clear of 2222 (agents), 2243-2246 (pool, rekeyed) and 3202/3204/3205.
TLS_PORT=3287
PREPARE_ONLY=0
TEST_ONLY=0
test_class="com.pocketshell.app.smoke.GatewayDockerJourneyTest"

usage() {
  cat <<'USAGE'
Usage: scripts/connected-js-gateway-docker.sh [--gateway-src DIR] [--suffix TOKEN] [--run-id ID]
                                              [--tls-port PORT] [--prepare-only|--test-only]

Build and run the packaged gateway journey (GatewayDockerJourneyTest).
Evidence lands in android/app/build/outputs/js-gateway/<run-id>/ and is checked
by scripts/check-js-gateway-results.py.

Options:
  --gateway-src DIR  PocketShell-io/pocketshell-gateway checkout at the pinned
                     commit (default: $POCKETSHELL_GATEWAY_SRC); needed to prepare
  --suffix TOKEN     Isolate the debug package; must contain "gwlane"
                     (default: i3086gwlane)
  --run-id ID        Unique artifact ID (generated by default)
  --tls-port PORT    Host port of the TLS front, mirrored on the emulator with
                     adb reverse (default: 3287)
  --prepare-only     Build the gateway binaries and the suffixed APKs, no AVD
  --test-only        Run the prepared build on one API 35+ emulator
USAGE
}

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --gateway-src) [[ $# -ge 2 ]] || fail '--gateway-src needs a directory'; GATEWAY_SRC="$2"; shift 2 ;;
    --suffix) [[ $# -ge 2 ]] || fail '--suffix needs a token'; SUFFIX="$2"; shift 2 ;;
    --run-id) [[ $# -ge 2 ]] || fail '--run-id needs a value'; RUN_ID="$2"; shift 2 ;;
    --tls-port) [[ $# -ge 2 ]] || fail '--tls-port needs a port'; TLS_PORT="$2"; shift 2 ;;
    --prepare-only) PREPARE_ONLY=1; shift ;;
    --test-only) TEST_ONLY=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

[[ "$SUFFIX" =~ ^[A-Za-z0-9._]*gwlane[A-Za-z0-9._]*$ ]] || fail "suffix must match [A-Za-z0-9._]+ and contain gwlane (got: $SUFFIX)"
[[ "$RUN_ID" =~ ^[A-Za-z0-9][A-Za-z0-9_-]{2,40}$ ]] || fail 'run ID must be 3-41 path-safe characters'
[[ "$TLS_PORT" =~ ^[0-9]{4,5}$ ]] && (( TLS_PORT >= 1024 && TLS_PORT <= 65535 )) || fail "bad --tls-port: $TLS_PORT"
case "$TLS_PORT" in 2222|3202|3204|3205) fail "--tls-port $TLS_PORT is reserved for another fixture" ;; esac
(( PREPARE_ONLY + TEST_ONLY <= 1 )) || fail '--prepare-only and --test-only cannot be combined'
[[ -x "$ROOT_DIR/android/gradlew" ]] || fail 'generated android/gradlew is missing'
[[ -x "$ROOT_DIR/scripts/check-js-gateway-results.py" ]] || fail 'gateway lane result verifier is missing'
[[ -x "$ROOT_DIR/scripts/gateway-lane-fixture.py" ]] || fail 'gateway lane controller is missing'
"$ROOT_DIR/scripts/check-js-gateway-results.py" --self-test
"$ROOT_DIR/scripts/gateway-lane-fixture.py" --self-test

source "$ROOT_DIR/scripts/lib/disk-preflight.sh"
source "$ROOT_DIR/scripts/lib/gradle-output-lock.sh"
source "$ROOT_DIR/scripts/lib/avd-lock.sh"
source "$ROOT_DIR/scripts/lib/android-input-preflight.sh"
source "$ROOT_DIR/scripts/lib/agents-fixture-version.sh"

pocketshell_disk_preflight "$ROOT_DIR/android" 'connected-js-gateway-docker.sh' || exit $?
pocketshell_acquire_gradle_output_lock "$ROOT_DIR/android" '' "connected-js-gateway-docker.sh suffix=$SUFFIX run=$RUN_ID"

LANE_BUILD="$ROOT_DIR/android/app/build/gateway-lane"
BIN_DIR="$LANE_BUILD/bin"
TLS_DIR="$LANE_BUILD/tls"
COMPOSE_FILE="$ROOT_DIR/tests/docker/gateway/docker-compose.yml"
PINNED_GATEWAY="$(tr -d '[:space:]' < "$ROOT_DIR/tests/docker/gateway/gateway-source.pin")"
[[ "$PINNED_GATEWAY" =~ ^[0-9a-f]{40}$ ]] || fail 'tests/docker/gateway/gateway-source.pin must hold one commit SHA'

if [[ "$TEST_ONLY" != 1 ]]; then
  [[ -n "$GATEWAY_SRC" ]] || fail 'pass the pocketshell-gateway checkout with --gateway-src (or POCKETSHELL_GATEWAY_SRC); the lane never skips'
  [[ -d "$GATEWAY_SRC/cmd/pocketshell-link" && -f "$GATEWAY_SRC/go.mod" ]] || fail "not a pocketshell-gateway checkout: $GATEWAY_SRC"
  actual="$(git -C "$GATEWAY_SRC" rev-parse HEAD 2>/dev/null || true)"
  [[ "$actual" == "$PINNED_GATEWAY" ]] || fail "gateway source is at ${actual:-<not a git checkout>}, the lane pins $PINNED_GATEWAY"
  [[ -z "$(git -C "$GATEWAY_SRC" status --porcelain --untracked-files=no)" ]] || fail "gateway source has local changes: $GATEWAY_SRC"
  command -v "$GO" >/dev/null 2>&1 || fail "the Go toolchain is required to build the gateway ($GO)"
  mkdir -p "$BIN_DIR"
  printf 'Building pocketshell-gateway %s (gateway, pocketshell-link) and the lane fixture tool\n' "$PINNED_GATEWAY"
  (cd "$GATEWAY_SRC" && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 "$GO" build -trimpath -o "$BIN_DIR/gateway" .)
  (cd "$GATEWAY_SRC" && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 "$GO" build -trimpath -o "$BIN_DIR/pocketshell-link" ./cmd/pocketshell-link)
  (cd "$ROOT_DIR/tests/docker/gateway/gwfixture" && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 "$GO" build -trimpath -o "$BIN_DIR/gwfixture" .)
  printf '%s\n' "$PINNED_GATEWAY" > "$BIN_DIR/gateway-source.commit"
  # A fresh test CA per prepared build; its private key is never written.
  mkdir -p "$TLS_DIR"
  "$BIN_DIR/gwfixture" certs -out "$TLS_DIR" -host localhost
  "${PNPM:-pnpm}" build:web
  "${PNPM:-pnpm}" cap:sync
  "$ROOT_DIR/android/gradlew" -p "$ROOT_DIR/android" :app:assembleDebug :app:assembleDebugAndroidTest \
    "-PpocketshellAppIdSuffix=$SUFFIX" "-PpocketshellGatewayTestCa=$TLS_DIR/ca.pem" \
    "-PpocketshellGatewayTestPort=$TLS_PORT" --stacktrace --console=plain
  # The native gateway allowlist (#3086 B1) admits the lane's TLS front only
  # because THIS build compiled it in: prove the build config says exactly that.
  build_config="$ROOT_DIR/android/app/build/generated/source/buildConfig/debug/com/pocketshell/app/BuildConfig.java"
  grep -Fq "GATEWAY_LANE_TEST_ORIGIN = \"wss://localhost:$TLS_PORT\";" "$build_config" \
    || fail "the gwlane build does not allow exactly wss://localhost:$TLS_PORT ($build_config)"
  printf '%s\n' "$TLS_PORT" > "$BIN_DIR/tls-port"
fi

if [[ "$PREPARE_ONLY" == 1 ]]; then
  printf 'PASS: gateway lane binaries and APKs prepared for suffix %s (gateway %s)\n' "$SUFFIX" "$PINNED_GATEWAY"
  exit 0
fi

for needed in gateway pocketshell-link gwfixture gateway-source.commit tls-port; do
  [[ -s "$BIN_DIR/$needed" ]] || fail "prepared gateway lane file missing: $BIN_DIR/$needed (run --prepare-only first)"
done
[[ "$(cat "$BIN_DIR/gateway-source.commit")" == "$PINNED_GATEWAY" ]] || fail 'the prepared gateway binaries are not the pinned commit; prepare again'
[[ "$(cat "$BIN_DIR/tls-port")" == "$TLS_PORT" ]] \
  || fail "the prepared build allows the lane origin on port $(cat "$BIN_DIR/tls-port"), not --tls-port $TLS_PORT; prepare with the same --tls-port"

for needed in ca.pem server.pem server.key; do
  [[ -s "$TLS_DIR/$needed" ]] || fail "prepared test-CA file missing: $TLS_DIR/$needed"
done

if [[ -z "${ANDROID_SERIAL:-}" ]]; then
  mapfile -t online_emulators < <("$ADB" devices | awk '$1 ~ /^emulator-/ && $2 == "device" { print $1 }')
  (( ${#online_emulators[@]} == 1 )) || fail "expected one online emulator or ANDROID_SERIAL; found ${#online_emulators[@]}"
  export ANDROID_SERIAL="${online_emulators[0]}"
fi
[[ "$("$ADB" -s "$ANDROID_SERIAL" get-state 2>/dev/null || true)" == device ]] \
  || fail "selected Android device is not online: $ANDROID_SERIAL"
device_api="$("$ADB" -s "$ANDROID_SERIAL" shell getprop ro.build.version.sdk | tr -d '\r')"
[[ "$device_api" =~ ^[0-9]+$ ]] && (( device_api >= 35 )) \
  || fail "the gateway journey requires API 35+; $ANDROID_SERIAL reports API ${device_api:-unknown}"

ARTIFACTS_DIR="$ROOT_DIR/android/app/build/outputs/js-gateway/$RUN_ID"
[[ ! -e "$ARTIFACTS_DIR" ]] || fail "refusing to overwrite existing run artifacts: $ARTIFACTS_DIR"
mkdir -p "$ARTIFACTS_DIR/instrumentation-results" "$ARTIFACTS_DIR/host"
# Secrets of the run (the broker signing key) stay outside the uploaded evidence.
STATE="$LANE_BUILD/runs/$RUN_ID"
mkdir -p "$STATE/broker" "$STATE/tls" "$STATE/enroll" "$STATE/bin"
cp "$TLS_DIR/server.pem" "$TLS_DIR/server.key" "$TLS_DIR/ca.pem" "$STATE/tls/"
cp "$BIN_DIR/gateway" "$BIN_DIR/pocketshell-link" "$BIN_DIR/gwfixture" "$STATE/bin/"
"$STATE/bin/gwfixture" brokerkey -out "$STATE/broker"

PROJECT="psgw$(printf '%s' "$RUN_ID" | tr -cd 'a-z0-9' | tail -c 24)"
DEVICE_ID="gwlane-$(printf '%s' "$RUN_ID" | tr -cd 'A-Za-z0-9' | tail -c 20 | tr 'A-Z' 'a-z')"
MISSING_DEVICE_ID="${DEVICE_ID}-missing"
SUBJECT="gwlane-sub-$(printf '%s' "$RUN_ID" | tr -cd 'a-z0-9' | tail -c 16)"
EMAIL="gwlane@example.test"
ISSUER="http://broker:8088"
SESSION_FOLDER="gwlane-$(printf '%s' "$RUN_ID" | tr -cd 'a-z0-9' | tail -c 16)-a"
export GWLANE_BIN="$STATE/bin" GWLANE_STATE="$STATE" GWLANE_EMAIL="$EMAIL" GWLANE_TLS_PORT="$TLS_PORT" GWLANE_DEVICE_ID="$DEVICE_ID"
compose() { docker compose -f "$COMPOSE_FILE" -p "$PROJECT" "$@"; }

controller_pid=""
reverse_added=0
fixture_stopped=0
collect_and_stop_fixture() {
  (( fixture_stopped == 0 )) || return 0
  fixture_stopped=1
  if [[ -n "$controller_pid" ]]; then kill "$controller_pid" 2>/dev/null || true; fi
  if (( reverse_added == 1 )); then "$ADB" -s "$ANDROID_SERIAL" reverse --remove "tcp:$TLS_PORT" >/dev/null 2>&1 || true; fi
  for service in gateway agent host tlsfront jwks; do
    compose logs --no-color --no-log-prefix "$service" > "$ARTIFACTS_DIR/host/$service.log" 2>&1 || true
  done
  compose down -v --remove-orphans >/dev/null 2>&1 || true
}
trap collect_and_stop_fixture EXIT

# The host: the agents fixture image (sshd, the pinned CLI and aplexer),
# version-matched to the APK so the app reaches its sessions.
export_agents_fixture_version "$ROOT_DIR/android/app/build/outputs/apk/debug/app-debug.apk"
docker image inspect pocketshell-test:agents >/dev/null 2>&1 \
  || docker compose -f "$ROOT_DIR/tests/docker/docker-compose.yml" build agents
compose up -d jwks gateway tlsfront host
for attempt in $(seq 1 90); do
  if curl -fsS --cacert "$STATE/tls/ca.pem" "https://localhost:$TLS_PORT/healthz" 2>/dev/null | grep -q '"tunnel":"enabled"'; then
    break
  fi
  (( attempt < 90 )) || fail 'the gateway never answered its health check through the TLS front'
  sleep 1
done
for attempt in $(seq 1 90); do
  if compose exec -T host sh -c 'test -s /etc/ssh/ssh_host_ed25519_key.pub && pgrep -x sshd >/dev/null'; then break; fi
  (( attempt < 90 )) || fail 'the host fixture never started sshd'
  sleep 1
done

# The independent pin source: the host's own key file, read on the host.
compose exec -T host cat /etc/ssh/ssh_host_ed25519_key.pub | awk '{print $1" "$2}' > "$STATE/enroll/host-key.pub"
grep -Eq '^ssh-ed25519 [A-Za-z0-9+/]+=*$' "$STATE/enroll/host-key.pub" || fail 'could not read the host key file'
"$STATE/bin/gwfixture" mint -key "$STATE/broker/broker-key.pem" -iss "$ISSUER" -sub "$SUBJECT" -email "$EMAIL" > "$STATE/enroll/token"
compose up -d agent
for attempt in $(seq 1 90); do
  if compose exec -T agent /gw/pocketshell-link show --config-dir /agent-state > "$ARTIFACTS_DIR/host/agent-show.txt" 2>/dev/null; then break; fi
  (( attempt < 90 )) || fail 'the host agent never enrolled'
  sleep 1
done
pin_json="$("$ROOT_DIR/scripts/gateway-lane-fixture.py" pinned-key --show-output "$ARTIFACTS_DIR/host/agent-show.txt")"
host_key_line="$(python3 -c 'import json,sys; print(json.loads(sys.argv[1])["hostKeyLine"])' "$pin_json")"
[[ "$host_key_line" == "$(cat "$STATE/enroll/host-key.pub")" ]] \
  || fail "the enrolled pin ($host_key_line) is not the host's own key file"
cp "$STATE/enroll/host-key.pub" "$ARTIFACTS_DIR/host/host-key.pub"
printf '%s\n' "$pin_json" > "$ARTIFACTS_DIR/host/pinned-key.json"

# A pin that is a real key, but not this host's.
ssh-keygen -q -t ed25519 -N '' -C gwlane-wrong-pin -f "$STATE/wrong-pin" </dev/null
wrong_pin="$(awk '{print $1" "$2}' "$STATE/wrong-pin.pub")"

# The session the journey lists and attaches.
compose exec -T host su testuser -s /bin/sh -c \
  "HOME=/home/testuser; cd; mkdir -p ~/$SESSION_FOLDER && pocketshell sessions create --json --cwd ~/$SESSION_FOLDER -- $SESSION_FOLDER >/dev/null" \
  || fail 'could not create the host session'

hello="$(python3 - "$DEVICE_ID" "$MISSING_DEVICE_ID" "$TLS_PORT" "$host_key_line" "$wrong_pin" "$SUBJECT" "$EMAIL" "$ISSUER" "$SESSION_FOLDER" <<'PY'
import json, sys
device, missing, port, pin, wrong, sub, email, issuer, folder = sys.argv[1:]
print(json.dumps({
    "deviceId": device, "missingDeviceId": missing, "serverUrl": f"wss://localhost:{port}", "tlsPort": int(port),
    "hostKeyLine": pin, "wrongHostKeyLine": wrong, "user": "testuser", "sub": sub, "email": email,
    "issuer": issuer, "sessionFolder": folder,
}))
PY
)"
printf '%s\n' "$hello" > "$ARTIFACTS_DIR/host/hello.json"

port_file="$STATE/controller-port"
"$ROOT_DIR/scripts/gateway-lane-fixture.py" serve --project "$PROJECT" --compose-file "$COMPOSE_FILE" \
  --state "$STATE" --journal "$ARTIFACTS_DIR/host/controller-journal.jsonl" --port-file "$port_file" \
  --hello "$hello" > "$ARTIFACTS_DIR/host/controller.log" 2>&1 &
controller_pid=$!
for _ in $(seq 1 50); do [[ -s "$port_file" ]] && break; sleep 0.1; done
[[ -s "$port_file" ]] || fail 'the gateway lane controller did not start'
controller_port="$(cat "$port_file")"

export POCKETSHELL_AVD_LOCK_CONTINUOUS=1
export POCKETSHELL_AVD_LOCK_FILE="$(pocketshell_avd_lock_file_for_serial "$ROOT_DIR" "$ANDROID_SERIAL")"
pocketshell_acquire_avd_lock "$ROOT_DIR"
pocketshell_assert_avd_lock_owned "$POCKETSHELL_AVD_LOCK_FILE"
# The AVD lock replaced the EXIT trap: one handler for everything this run holds.
on_exit() {
  collect_and_stop_fixture
  pocketshell_release_all
}
trap on_exit EXIT

pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" reverse "tcp:$TLS_PORT" "tcp:$TLS_PORT" >/dev/null
reverse_added=1
pocketshell_android_apply_lane_settings "$ADB" "$ANDROID_SERIAL" "$ARTIFACTS_DIR/lane-settings.txt" \
  || fail "could not apply the lane input settings on $ANDROID_SERIAL"
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" logcat -c >/dev/null 2>&1 || true

RESULTS_DIR="$ROOT_DIR/android/app/build/outputs/androidTest-results/connected/debug"
rm -rf -- "$RESULTS_DIR"
printf 'Running packaged gateway journey on %s (API %s), suffix %s, run %s, gateway %s\n' \
  "$ANDROID_SERIAL" "$device_api" "$SUFFIX" "$RUN_ID" "$PINNED_GATEWAY"
test_status=0
pocketshell_run_without_avd_lock_fd "$ROOT_DIR/android/gradlew" -p "$ROOT_DIR/android" :app:connectedDebugAndroidTest \
  "-PpocketshellAppIdSuffix=$SUFFIX" "-PpocketshellGatewayTestCa=$TLS_DIR/ca.pem" \
  "-PpocketshellGatewayTestPort=$TLS_PORT" \
  "-Pandroid.testInstrumentationRunnerArguments.class=$test_class" \
  "-Pandroid.testInstrumentationRunnerArguments.gatewayRunId=$RUN_ID" \
  "-Pandroid.testInstrumentationRunnerArguments.gatewayControllerPort=$controller_port" \
  "-Pandroid.testInstrumentationRunnerArguments.gatewayBrokerKeyPkcs8Base64=$(cat "$STATE/broker/broker-key.pkcs8.b64")" \
  "-Pandroid.testInstrumentationRunnerArguments.gatewayBrokerKid=$(cat "$STATE/broker/broker-kid")" \
  --stacktrace --console=plain || test_status=$?

shopt -s nullglob
junit_files=("$RESULTS_DIR"/TEST-*.xml)
shopt -u nullglob
(( ${#junit_files[@]} > 0 )) && cp -a -- "${junit_files[@]}" "$ARTIFACTS_DIR/instrumentation-results/"
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" logcat -d -v threadtime > "$ARTIFACTS_DIR/logcat.txt" 2>&1 || true
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" exec-out screencap -p > "$ARTIFACTS_DIR/final-screen.png" 2>/dev/null || true
mkdir -p "$ARTIFACTS_DIR/screenshots"
for shot in pin-mismatch device-offline terminal-io after-reconnect; do
  pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" pull "/data/local/tmp/gwlane-$shot.png" "$ARTIFACTS_DIR/screenshots/$shot.png" >/dev/null 2>&1 || true
  pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" shell rm -f "/data/local/tmp/gwlane-$shot.png" >/dev/null 2>&1 || true
done
collect_and_stop_fixture

(( test_status == 0 )) || fail "connected gateway journey failed (exit $test_status); evidence in $ARTIFACTS_DIR"

"$ROOT_DIR/scripts/check-js-gateway-results.py" \
  --results-dir "$ARTIFACTS_DIR/instrumentation-results" \
  --host-dir "$ARTIFACTS_DIR/host"
printf 'PASS: packaged gateway journey completed. Artifacts: %s\n' "$ARTIFACTS_DIR"
