#!/usr/bin/env bash
# Run the packaged JS settings/support journeys (#2861: J16 support and
# diagnostic export, J24 settings reach with Android Back) on one owned API 35+
# AVD, then collect same-run JUnit XML and screenshots and check them.

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$ROOT_DIR"

ANDROID_SDK="${ANDROID_SDK:-${ANDROID_SDK_ROOT:-${ANDROID_HOME:-/home/alexey/Android/Sdk}}}"
ADB="${ADB:-$ANDROID_SDK/platform-tools/adb}"
SUFFIX="i2861settings"
RUN_ID="js2861-$(date -u '+%Y%m%dT%H%M%S')"
PREPARE_ONLY=0
TEST_ONLY=0
PORT=""
CONTAINER=""
test_class="com.pocketshell.app.smoke.JsSettingsSupportJourneyTest"

usage() {
  cat <<'USAGE'
Usage: scripts/connected-js-settings.sh --port PORT --container NAME [--suffix TOKEN] [--run-id ID] [--prepare-only|--test-only]

Build and run the packaged J16/J24 settings and support journeys
(JsSettingsSupportJourneyTest). Evidence lands in
android/app/build/outputs/js-settings/<run-id>/ and is checked by
scripts/check-js-settings-results.py.

The reconnect-when-I-return journey attaches a real session on the Docker
agents fixture; its session ID is checked independently on the host.

Options:
  --port PORT      Docker agents fixture SSH port on the host (10.0.2.2 from the AVD)
  --container NAME Docker agents fixture container, for the host session oracle
  --suffix TOKEN   Isolate the debug package (default: i2861settings)
  --run-id ID      Unique artifact ID (generated by default)
  --prepare-only   Build the suffixed app and androidTest APKs, without an AVD
  --test-only      Run the already-prepared APKs on one API 35+ emulator
USAGE
}

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --suffix) [[ $# -ge 2 ]] || fail '--suffix needs a token'; SUFFIX="$2"; shift 2 ;;
    --run-id) [[ $# -ge 2 ]] || fail '--run-id needs a value'; RUN_ID="$2"; shift 2 ;;
    --port) [[ $# -ge 2 ]] || fail '--port needs a value'; PORT="$2"; shift 2 ;;
    --container) [[ $# -ge 2 ]] || fail '--container needs a value'; CONTAINER="$2"; shift 2 ;;
    --prepare-only) PREPARE_ONLY=1; shift ;;
    --test-only) TEST_ONLY=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

[[ "$SUFFIX" =~ ^[A-Za-z0-9._]+$ ]] || fail "suffix must match [A-Za-z0-9._]+ (got: $SUFFIX)"
[[ "$RUN_ID" =~ ^[A-Za-z0-9][A-Za-z0-9_-]{2,48}$ ]] || fail 'run ID must be 3-49 path-safe characters'
(( PREPARE_ONLY + TEST_ONLY <= 1 )) || fail '--prepare-only and --test-only cannot be combined'
[[ -x "$ROOT_DIR/android/gradlew" ]] || fail 'generated android/gradlew is missing'
[[ -x "$ROOT_DIR/scripts/check-js-settings-results.py" ]] || fail 'packaged settings result verifier is missing'
"$ROOT_DIR/scripts/check-js-settings-results.py" --self-test

source "$ROOT_DIR/scripts/lib/disk-preflight.sh"
source "$ROOT_DIR/scripts/lib/gradle-output-lock.sh"
source "$ROOT_DIR/scripts/lib/avd-lock.sh"
source "$ROOT_DIR/scripts/lib/js-fixture-port-lock.sh"

pocketshell_disk_preflight "$ROOT_DIR/android" 'connected-js-settings.sh' || exit $?
pocketshell_acquire_gradle_output_lock "$ROOT_DIR/android" '' "connected-js-settings.sh suffix=$SUFFIX run=$RUN_ID"

if [[ "$TEST_ONLY" != 1 ]]; then
  "$ROOT_DIR/scripts/assemble-debug.sh" --suffix "$SUFFIX"
  "$ROOT_DIR/android/gradlew" -p "$ROOT_DIR/android" :app:assembleDebugAndroidTest \
    "-PpocketshellAppIdSuffix=$SUFFIX" --stacktrace --console=plain
fi

if [[ "$PREPARE_ONLY" == 1 ]]; then
  printf 'PASS: packaged JS settings journey APKs prepared for suffix %s\n' "$SUFFIX"
  exit 0
fi

[[ "$PORT" =~ ^[0-9]+$ ]] || fail '--port is required for the Docker-backed reconnect journey'
[[ "$CONTAINER" =~ ^[A-Za-z0-9_.-]+$ ]] || fail '--container is required for the host session oracle'
[[ "$(docker inspect -f '{{.State.Running}}' "$CONTAINER" 2>/dev/null || true)" == true ]] \
  || fail "Docker agents fixture container is not running: $CONTAINER"
[[ -f "$ROOT_DIR/tests/docker/test_key" ]] || fail 'committed Docker test key is missing'
ssh_key_base64="$(base64 -w0 "$ROOT_DIR/tests/docker/test_key")"

if [[ -z "${ANDROID_SERIAL:-}" ]]; then
  mapfile -t online_emulators < <("$ADB" devices | awk '$1 ~ /^emulator-/ && $2 == "device" { print $1 }')
  (( ${#online_emulators[@]} == 1 )) || fail "expected one online emulator or ANDROID_SERIAL; found ${#online_emulators[@]}"
  export ANDROID_SERIAL="${online_emulators[0]}"
fi
[[ "$("$ADB" -s "$ANDROID_SERIAL" get-state 2>/dev/null || true)" == device ]] \
  || fail "selected Android device is not online: $ANDROID_SERIAL"
device_api="$("$ADB" -s "$ANDROID_SERIAL" shell getprop ro.build.version.sdk | tr -d '\r')"
[[ "$device_api" =~ ^[0-9]+$ ]] && (( device_api >= 35 )) \
  || fail "the settings journeys require API 35+; $ANDROID_SERIAL reports API ${device_api:-unknown}"

export POCKETSHELL_AVD_LOCK_CONTINUOUS=1
export POCKETSHELL_AVD_LOCK_FILE="$(pocketshell_avd_lock_file_for_serial "$ROOT_DIR" "$ANDROID_SERIAL")"
pocketshell_acquire_avd_lock "$ROOT_DIR"
pocketshell_assert_avd_lock_owned "$POCKETSHELL_AVD_LOCK_FILE"
# Own the Docker fixture for the whole run: a sibling lane on the same port
# would open a second SSH socket that the host oracle attributes to this app.
pocketshell_acquire_js_fixture_port_lock "$PORT" || fail "agents fixture port $PORT is busy"

RESULTS_DIR="$ROOT_DIR/android/app/build/outputs/androidTest-results/connected/debug"
ARTIFACTS_DIR="$ROOT_DIR/android/app/build/outputs/js-settings/$RUN_ID"
[[ ! -e "$ARTIFACTS_DIR" ]] || fail "refusing to overwrite existing run artifacts: $ARTIFACTS_DIR"
rm -rf -- "$RESULTS_DIR"
mkdir -p "$ARTIFACTS_DIR/instrumentation-results" "$ARTIFACTS_DIR/device-screenshots"

SCREENSHOT_DIR="/sdcard/Pictures/PocketShell/JsSettings/$RUN_ID"
printf 'Running packaged JS settings journeys on %s (API %s), suffix %s, run %s\n' \
  "$ANDROID_SERIAL" "$device_api" "$SUFFIX" "$RUN_ID"
test_status=0
pocketshell_run_without_avd_lock_fd "$ROOT_DIR/android/gradlew" -p "$ROOT_DIR/android" :app:connectedDebugAndroidTest \
  "-PpocketshellAppIdSuffix=$SUFFIX" \
  "-Pandroid.testInstrumentationRunnerArguments.class=$test_class" \
  "-Pandroid.testInstrumentationRunnerArguments.screenshotRunId=$RUN_ID" \
  -Pandroid.testInstrumentationRunnerArguments.sshHost=10.0.2.2 \
  "-Pandroid.testInstrumentationRunnerArguments.sshPort=$PORT" \
  "-Pandroid.testInstrumentationRunnerArguments.sshPrivateKeyBase64=$ssh_key_base64" \
  --stacktrace --console=plain || test_status=$?

shopt -s nullglob
junit_files=("$RESULTS_DIR"/TEST-*.xml)
shopt -u nullglob
(( ${#junit_files[@]} > 0 )) && cp -a -- "${junit_files[@]}" "$ARTIFACTS_DIR/instrumentation-results/"
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" logcat -d -v threadtime -t 4000 > "$ARTIFACTS_DIR/logcat.txt" 2>&1 || true
while IFS= read -r screenshot; do
  screenshot="${screenshot%$'\r'}"
  [[ "$screenshot" == *.png ]] || continue
  pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" pull "$SCREENSHOT_DIR/$screenshot" "$ARTIFACTS_DIR/device-screenshots/$screenshot" >/dev/null \
    || fail "could not retrieve packaged screenshot: $screenshot"
done < <(pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" shell "ls '$SCREENSHOT_DIR' 2>/dev/null" || true)

relative_screenshot_dir="Pictures/PocketShell/JsSettings/$RUN_ID/"
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" shell \
  "content delete --uri content://media/external/images/media --where \"relative_path='$relative_screenshot_dir'\"" >/dev/null 2>&1 || true
pocketshell_run_without_avd_lock_fd "$ADB" -s "$ANDROID_SERIAL" shell "rm -rf '$SCREENSHOT_DIR'" >/dev/null 2>&1 || true

(( test_status == 0 )) || fail "connected settings journeys failed (exit $test_status); evidence in $ARTIFACTS_DIR"

# Independent host oracle for the reconnect journey: the evidence line the
# test logged, and the live session list read straight from the Docker host.
python3 - "$ARTIFACTS_DIR/logcat.txt" "$ARTIFACTS_DIR/reconnect-evidence.json" <<'PY'
import json, re, sys
matches = [re.search(r"PocketshellSettingsEvidence.*RECONNECT (\{.*\})", line) for line in open(sys.argv[1], encoding="utf-8", errors="replace")]
found = [m.group(1) for m in matches if m]
if len(found) != 1:
    sys.exit(f"FAIL: expected one RECONNECT evidence line in logcat, found {len(found)}")
json.dump(json.loads(found[0]), open(sys.argv[2], "w", encoding="utf-8"), indent=2)
PY
pocketshell_run_without_avd_lock_fd docker exec -u testuser -e HOME=/home/testuser "$CONTAINER" /usr/local/bin/pocketshell-real sessions list --json \
  > "$ARTIFACTS_DIR/host-pocketshell-sessions-list.json" || fail 'could not read the Docker host session list'

"$ROOT_DIR/scripts/check-js-settings-results.py" \
  --results-dir "$ARTIFACTS_DIR/instrumentation-results" \
  --screenshots-dir "$ARTIFACTS_DIR/device-screenshots" \
  --reconnect-evidence "$ARTIFACTS_DIR/reconnect-evidence.json" \
  --host-listing "$ARTIFACTS_DIR/host-pocketshell-sessions-list.json"
printf 'PASS: packaged JS settings journeys completed. Artifacts: %s\n' "$ARTIFACTS_DIR"
